// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-K5pJh3qVk-W6bi48HjOcjctqfTaeAhM',
    appId: '1:842783323477:web:7d187e4c4e43202a57abdc',
    messagingSenderId: '842783323477',
    projectId: 'fujii-photo-calendar',
    authDomain: 'fujii-photo-calendar.firebaseapp.com',
    storageBucket: 'fujii-photo-calendar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqLIjzWF5zFQ0XjgJzlHepPz-m6u2jEqI',
    appId: '1:842783323477:android:a21fc117d02784de57abdc',
    messagingSenderId: '842783323477',
    projectId: 'fujii-photo-calendar',
    storageBucket: 'fujii-photo-calendar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnAVnKxvf3yGhFwcIQKftEvzdbbYy7jkQ',
    appId: '1:842783323477:ios:5aafb3ad7208a81657abdc',
    messagingSenderId: '842783323477',
    projectId: 'fujii-photo-calendar',
    storageBucket: 'fujii-photo-calendar.firebasestorage.app',
    iosBundleId: 'com.example.fujiiPhotoCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnAVnKxvf3yGhFwcIQKftEvzdbbYy7jkQ',
    appId: '1:842783323477:ios:5aafb3ad7208a81657abdc',
    messagingSenderId: '842783323477',
    projectId: 'fujii-photo-calendar',
    storageBucket: 'fujii-photo-calendar.firebasestorage.app',
    iosBundleId: 'com.example.fujiiPhotoCalendar',
  );
}
