include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_late: true
    use_super_parameters: true

# (T006) 将来 import_lint 도입予定: 層間 (core -> data -> domain -> presentation -> providers) 制約を import_lint.yaml で管理予定。
