# (T004) build_runner / freezed / json_serializable 初期設定
# 必要に応じて将来 options を拡張

targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/**.dart
      json_serializable:
        options:
          explicit_to_json: true
