openapi: 3.0.3
info:
  title: Month Calendar Local Contracts
  version: 0.1.0
servers: []
paths: {}
components:
  schemas:
    PhotoEntity:
      type: object
      description: "正規化後にクライアントで扱う写真エンティティ（Firestoreドキュメントを一段マッピング）"
      properties:
        id:
          type: string
          description: ファイル名/FirestoreドキュメントID
        type:
          type: string
          description: 写真種別 (Firestoreの 'type' フィールドをそのまま利用)
          enum: [fujii-photos, user-photos]
        month:
          type: integer
          minimum: 1
          maximum: 12
          description: 撮影月 (capturedAt のタイムゾーン基準)
        monthKey:
          type: string
          pattern: "^(0[1-9]|1[0-2])$"
          description: ゼロ詰めMM（導出フィールド）
        capturedAt:
          type: string
          format: date-time
          description: 撮影日時（TZ情報込）
        url:
          type: string
          format: uri
          description: 公開/ダウンロード URL (Emulator/本番で差異あり)
        priority:
          type: integer
          minimum: 0
          description: 表示優先度（導出: fujii-photos=10, user-photos=0）
        memo:
          type: string
          description: 付随メモ（現状UI未使用）
        updatedAt:
          type: string
          format: date-time
          description: Firestore更新時刻（キャッシュ整合用）
      required: [id, type, month, capturedAt, url]
    CalendarViewState:
      type: object
      description: 月ビュー表示用の集約状態（UIコンポーネント間で共有）
      properties:
        month:
          type: integer
          minimum: 1
          maximum: 12
        photos:
          type: array
          items:
            $ref: '#/components/schemas/PhotoEntity'
        slideshowIntervalMs:
          type: integer
          example: 5000
        transitionMs:
          type: integer
          example: 300
        hasStudioShot:
          type: boolean
        placeholders:
          type: array
          items:
            type: string
        roleVariant:
          type: string
          enum: [viewer, owner]
      required: [month, photos]
